# Generated by Django 2.1.1 on 2018-12-26 08:52

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Category',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=Home.models.product_media_path),
        ),
        migrations.AlterField(
            model_name='Category',
            name='thumbnail',
            field=models.ImageField(upload_to=Home.models.category_icon_path),
        ),
    ]
