# Generated by Django 2.1.4 on 2019-01-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20181226_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
